Repository seawind543/react-token-input, pull requests merged in 2021-12, with the labels that each got.

#55 [#51] fix: ESC Predefined KeyDown Event behavior
  docs/bundle.js
  docs/index.html
  lib/index.js
  lib/index.js.map
  src/TokenInput.jsx
  src/hooks/useTokenEdit.js
  src/hooks/useTokenEdit.test.js
Labels: bug

#53 Fix webpack config globalObject for NextJS / SSR compatibility
  lib/index.js
  lib/index.js.map
  webpack.config.js
Labels: enhancement, runtime issue

#56 feat: export the KEY_DOWN_HANDLER_CONFIG_OPTION
  README.md
  docs/bundle.js
  docs/index.html
  examples/ExampleSpecialKeyDown/ExampleSpecialKeyDown.jsx
  lib/index.js
  lib/index.js.map
  src/TokenInput.jsx
  src/constants.js
  src/hooks/usePredefinedKeyDownHandlers.js
  src/hooks/usePredefinedKeyDownHandlers.test.js
  src/index.js
Labels: enhancement
